#!/usr/bin/env bash

# Required variables.
: ${GLI_PROGNAME="gli"};
: ${GLI_VERSION="0.1"};
: ${GLI_MENUSDIR="/usr/share/${GLI_PROGNAME}-${GLI_VERSION}"};

# Load variables.
. ${GLI_MENUSDIR}/variables.bash

# Ignore flags.
while getopts ":h:" ignored; do
    :
done
shift $(( $OPTIND - 1 ))

# Load main menu by default.
GLI_MENU=${1:-main}; shift

echo "Opening ${GLI_MENUSDIR}/${GLI_MENU}.bash" >> /tmp/gli.log

exec "${GLI_MENUSDIR}/${GLI_MENU}.bash" "$@" 2> /dev/null
