#!/usr/bin/env bash

# Required variables.
: "${GLI_PROGNAME=gli}"
: "${GLI_VERSION=0.1}"
: "${GLI_SCRIPTSDIR=./scripts}"
export GLI_SCRIPTSDIR

# Load variables and functions.
. "${GLI_SCRIPTSDIR}"/varfunc.bash

# Parse opts.
while getopts ":d" opt; do
    case ${opt} in
        d)
            export GLI_DEBUG=1
            gli_debug "GLI started!"
        ;;
        *)
            echo "GLI: the Gentoo Linux Installer.

usage: $(basename "$0") [-d]

  -d  Run GLI in debug mode (print info in ${GLI_LOG_FILE})."
            exit 1
        ;;
  esac
done
shift $(( OPTIND - 1 ))

# Load main menu by default.
GLI_SCRIPT=${1:-main}; shift

if [[ ${GLI_DEBUG} -eq 1 ]]; then
    gli_debug "main: opening ${GLI_SCRIPTSDIR}/${GLI_SCRIPT}"
fi

exec "${GLI_SCRIPTSDIR}/${GLI_SCRIPT}.bash" "$@" 2> /dev/null
