=head1 Introduction

GLI is a text user interface that simplifies and automates the installation of
Gentoo Linux as described in the Gentoo Linux handbook. The user is prompted
with textboxes and inputboxes to fill in so that GLI can perform the
installation as described in the Gentoo Linux Handbook.

GLI is not meant to be a replacement for the Gentoo Linux Handbook but solely
an aid for medium to heavy Linux gurus to speed up a Gentoo Linux installation.
When you just start out in the Linux world and perform your first Gentoo
installation, reading along the Handbook and installing Gentoo Linux is indeed
fun and a great learning experience. When you've done it for the umpteenth time
and know the process inside out, there isn't really much to learn anymore.
Installing Gentoo Linux is more like a chore then. That's where GLI steps into the scene.

GLI is built with Python and the urwid library.

=head2 Notes

A lot of ideas have been taken from FreeBSD's bsdinstall(8).

=head2 Author

Patrice Clement E<lt>monsieurp@gentoo.orgE<gt>

=cut
